### ISSUE TITLE
Add build watch momde

### ISSUE THREAD

**Issue by nandorojo** [react-native-community/bob#88] opened 2020-09-14 23:21 UTC
# Feature request

I'd love to be able to run `bob build --watch`, and for it to rebuild every time there is a change.

## Why it is needed

I'm using `bob` in a monorepo, and I have multiple example apps (`next`, `expo`, `gatsby`) that need to update when I make changes. Currently I need to run `bob build` each time.

## Possible implementation

I'm not sure how other repos do this, but whenever there is a file saved, it could run `bob build`.

### Code sample

```diff
- bob build
+ bob build --watch
```

**Comment by nandorojo** [comment] 2020-09-14 23:22
Original issue where this is concerned is from my library Dripsy: https://github.com/nandorojo/dripsy/pull/32

**Comment by Krizzu** [comment] 2020-09-15 07:40
Hey,

This is a duplicate of #81 - have a look there for Satya suggestion on that.

**Closed by Krizzu** 2020-09-15 07:40 UTC
